# The post_build phase includes creating or updating a CloudFormation stack for
# the CloudFront distribution, Cognito User Pool, and Lambda@Edge function. The
# cloudfront-cognito-lambdaedge.yml file should contain the necessary
# CloudFormation configuration for creating these resources. 
#
# The CloudFront distribution should be configured to use the S3 bucket hosting
# the Docusaurus documentation as its origin, and the Lambda@Edge function
# should be deployed in the Viewer Request event to handle authentication and
# authorization. 
#
# You can refer to this [AWS Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-how-to-use-lambdaedge-and-json-web-tokens-to-enhance-web-application-security/)
# for more details on how to set up CloudFront, Cognito, and Lambda@Edge for
# securing access to your documentation.

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "$(date -u): Installing dependencies..."
      - npm install
      - echo "$(date -u): Installing Docusaurus..."
      - cd docs
      - npm install --omit=dev
      - cd ..

  pre_build:
    commands:
      - echo "$(date -u): Linting and running tests..."
      - npm run lint
      # - npm test # no tests in this repo yet... should add some!

  build:
    commands:
      - echo "$(date -u): Building the Node.js API service..."
      - rm -rf node_modules
      - npm install --omit=dev
      - npm run build --omit=dev
      - echo "$(date -u): Creating deployment package..."
      - zip -r deployment-package.zip dist/ node_modules/
      - echo "$(date -u): Building the Docusaurus documentation..."
      - cd ../docs
      - npm run build --omit=dev
      - cd ..

  post_build:
    commands:
      - echo "$(date -u): Post-build steps..."
      - echo "$(date -u): Uploading deployment package to S3..."
      - aws s3 cp deployment-package.zip s3://$CFNS3BUCKET/deployment-packages/
      - echo "$(date -u): Uploading Docusaurus documentation to S3..."
      - echo "$(date -u): Deploying Lambda function and API Gateway using AWS SAM..."
      - aws cloudformation package --template-file devops/prod-api-cfn.yml --output-template-file packaged-template.yml --s3-bucket $CFNS3BUCKET --s3-prefix templates/
      - aws cloudformation deploy --template-file packaged-template.yml --stack-name $STACKNAME --capabilities CAPABILITY_NAMED_IAM --parameter-overrides S3BUCKET=$CFNS3BUCKET StackName=$STACKNAME
      - echo "$(date -u): Syncing the Docusaurus documentation to S3 bucket $STACKNAME-docs"
      - aws s3 sync docs/build/ s3://$STACKNAME-docs/ --recursive --delete
      - echo "$(date -u): Clearing the CloudFront distribution cache"
      - aws cloudfront create-invalidation --distribution-id ${CDN_DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
    - devops/prod-api-cfn.yml
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*
    - docs/node_modules/**/*
