AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample Node.js-based API service on AWS Lambda and API Gateway


Resources:
  NodeJsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://my-bucket/deployment-packages/deployment-package.zip
      Handler: dist/lambda.handler
      Runtime: nodejs12.x
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


Outputs:
  ApiGatewayUrl:
    Description: "API Gateway base URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
