AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys a serverless AWS Fargate web service.
             The service tasks use an NGINX reverse proxy in front of the application.
Parameters:
  AppImageUrl:
    Type: String
    Description: The url of a docker image that contains the application process that
                 will handle the traffic for this service
  NginxImageUrl:
    Type: String
    Description: The url of a docker image that provides the NGINX reverse proxy
  TeamName:
    Type: String
    Default: "team-1"
    Description: Team name
  SSLCertificateArn:
    Type: String
    Description: ARN of the existing certificate.
  SubDomainName:
    Type: String
    Default: zap.pcloud.practeraco.de
    Description: The subdomain name (e.g., app.example.com)
  Client:
    Type: String
    Default: "skillsbuild"
    Description: WBLA or IBM
  RootDomainName:
    Type: String
    Default: pcloud.practeraco.de 
    Description: The root domain name (e.g., example.com)
  PAT:
    Type: String
    Description: Github PAT

Resources:
  # CertificateStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: acm-zone.yml
  # The networking configuration. This creates an isolated
  # network specific to this particular environment
  ## Note commented this one out: Reuse existing vpc


  #Uncomment if required to crete only once
  # VpcStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: vpc.yml

  # This stack contains the Amazon ECS cluster itself
        
  ClusterStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cluster.yml
      Parameters:
        TeamName: !Ref TeamName
        Client: !Ref Client
  # # This stack contains the container deployment
  ServiceStack:
    DependsOn: ClusterStack
    Type: AWS::Serverless::Application
    Properties:
      Location: service.yml
      Parameters:
       # for pcloud-sandbox
        # VpcId: vpc-035c63bb8c483a219
         # For cyber-sandbox
        VpcId: vpc-056af225c9a7b5992
        # for pcloud-sandbox
        # PublicSubnetIds: subnet-0371146de19b72726,subnet-05708a77ebaef3251
        # For cyber-sandbox
        PublicSubnetIds: subnet-0a7b5dacf14b96cef,subnet-0283a9d16378baeb9
        ClusterName: !GetAtt ClusterStack.Outputs.ClusterName
        ECSTaskExecutionRole: !GetAtt ClusterStack.Outputs.ECSTaskExecutionRole
        AppImageUrl: !Ref AppImageUrl
        NginxImageUrl: !Ref NginxImageUrl
        SSLCertificateArn: !Ref SSLCertificateArn
        TeamName: !Ref TeamName
        SubDomainName: !Ref SubDomainName
        Client: !Ref Client
        RootDomainName: !Ref RootDomainName

  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda-deletion.yml
      Parameters:
        TeamName: !Ref TeamName
        Client: !Ref Client
        PAT: !Ref PAT