AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys a serverless AWS Fargate web service.
             The service tasks use an NGINX reverse proxy in front of the application.
Parameters:
  AppImageUrl:
    Type: String
    Description: The url of a docker image that contains the application process that
                 will handle the traffic for this service
  NginxImageUrl:
    Type: String
    Description: The url of a docker image that provides the NGINX reverse proxy
  TeamName:
    Type: String
    Default: "team-1"
    Description: Team name
  SSLCertificateArn:
    Type: String
    Description: ARN of the existing certificate.
  SubDomainName:
    Type: String
    Default: zap.cybersec.practeraco.de
    Description: The subdomain name (e.g., app.example.com)
  Client:
    Type: String
    Default: "skillsbuild"
    Description: WBLA or IBM
Resources:
  # CertificateStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: acm-zone.yml
  # The networking configuration. This creates an isolated
  # network specific to this particular environment
  ## Note commented this one out: Reuse existing vpc
  # VpcStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: vpc.yml

  # This stack contains the Amazon ECS cluster itself
  ClusterStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cluster.yml
      Parameters:
        TeamName: !Ref TeamName
        Client: !Ref Client
  # # This stack contains the container deployment
  ServiceStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service.yml
      Parameters:
        VpcId: !ImportValue CYBERSECURITY-VPC-ID
        PublicSubnetIds: !ImportValue CYBERSECURITY-VPC-PUBLICSUBNETS
        ClusterName: !GetAtt ClusterStack.Outputs.ClusterName
        ECSTaskExecutionRole: !GetAtt ClusterStack.Outputs.ECSTaskExecutionRole
        AppImageUrl: !Ref AppImageUrl
        NginxImageUrl: !Ref NginxImageUrl
        SSLCertificateArn: !Ref SSLCertificateArn
        TeamName: !Ref TeamName
        SubDomainName: !Ref SubDomainName
        Client: !Ref Client