---
name: 'Activate Shutdown or Restart CyberSec Infra'

on:
  push:
    branches:
      - feat/workflow
  workflow_dispatch:

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "Hello World!"
