---
name: "Activate Shutdown or Restart CyberSec Infra"

on:
  push:
    branches:
      - feat/workflow

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "hey"
      # - name: Configure AWS credentials pcloud CyberSec
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.CYBERSEC_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.CYBERSEC_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
